name: Deploy via SSH
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 167.99.66.1 >> ~/.ssh/known_hosts
        
    - name: SSH into remote VM and run commands
      run: |
        ssh root@167.99.66.1 -p 3030 "uptime && whoami && df -h"
